### PR TITLE
feat: implement Drugs class; test: add a single starter test case for…

### PR DESCRIPTION
**Pull request by jiatuoz2**
… Drugs

I added 3 functions for Drugs class, which are add, delete, and getInteraction for a drug. The assumption is that all drugs reside in a collection called "drugs". In the future, I believe whenever an interaction is added through the API endpoint, we should check if either drugA or drugB already exists in the drugs collection. If not, we can add a new drug. The same goes for removeInteraction. I added a unit test just as a starter template.

### CODE REVIEW

**Comment by t0mmylam** [comment]
regarding the checking if the interactions exist, I already have added that logic in my PR

**Comment by samjoredw** [comment]
> regarding the checking if the interactions exist, I already have added that logic in my PR

So we have a duplicate method?

**Comment by t0mmylam** [comment]
> > regarding the checking if the interactions exist, I already have added that logic in my PR
> 
> So we have a duplicate method?

No, he mentioned in the future and from looking at the code it doesn't seem like his method checks for already existing interactions in the db. I implemented it so that my endpoint does check though already

**Review by samjoredw — COMMENTED** [review]
we will need to add the JSON file to be tracked but for now it passes local test and looks good.

**Pull request merged**
